print("| welcome to calculator app |\n")
num1=float(input("first number :"))
num2=float(input("second number :"))
print("|==================|")
print("adding:"+str(num1+num2) )
print("dec:"+str(num1-num2) )
print("mult:"+str(num1*num2) )
print("div:"+str(num1/num2) )
print("des:"+str(num1%num2) )